import { Icon } from "./Icons";
import { HighlightBox, StatusBadge } from "./SlideShell";
import { riskRows, ticketRows } from "@/data/slides";

function AppHeader({ active = "Dashboard" }: { active?: string }) {
  return <div className="app-header"><div className="app-brand"><span>RJ</span><b>Roo-Jaeng</b></div><nav>{["Dashboard", "Tickets", "Reports", "Zabbix Risk"].map(item => <span className={active === item ? "active" : ""} key={item}>{item}</span>)}</nav><div className="app-user"><Icon name="bell"/><span>NK</span></div></div>;
}

export function BrowserMockup({ children, title = "Roo-Jaeng" }: { children: React.ReactNode; title?: string }) {
  return <div className="browser-mockup"><div className="browser-bar"><div className="traffic"><i/><i/><i/></div><div className="address"><Icon name="shield"/> roo-jaeng.com <span>{title}</span></div><div className="browser-menu">•••</div></div><div className="browser-content">{children}</div></div>;
}

export function IPhoneMockup({ children, label, compact = false }: { children: React.ReactNode; label?: string; compact?: boolean }) {
  return <div className={`phone-unit ${compact ? "phone-unit--compact" : ""}`}>{label && <div className="phone-label">{label}</div>}<div className="iphone"><div className="dynamic-island"/><div className="phone-status"><b>09:41</b><span>● ◒ ︿</span></div><div className="phone-screen">{children}</div><div className="home-indicator"/></div></div>;
}

export function MiniTicketCard() {
  return <div className="mini-ticket"><div className="mini-ticket-top"><span>#4342</span><StatusBadge status="Closed"/></div><h4>/var filesystem usage</h4><p>HSVCRP01 · Zabbix</p><div className="mini-ticket-foot"><span className="severity-dot"/> Warning <span>Assigned: Thyme</span></div></div>;
}

export function NotificationCard() {
  return <div className="ios-notification"><div className="notification-head"><span className="notification-logo">RJ</span><b>ROO-JAENG</b><small>now</small></div><strong>Problem · Warning</strong><p>/var filesystem 95% on HSVCRP01</p><div className="notification-meta">Ticket #4342 · Tap to open</div></div>;
}

export function DashboardMockup() {
  const bars = [42, 56, 38, 71, 64, 82, 68, 88, 74, 92, 78, 86];
  return <BrowserMockup title="Dashboard"><AppHeader/><div className="app-page dashboard"><div className="mock-title"><div><small>ROO-JAENG OPERATIONS</small><h3>Incident Dashboard</h3></div><button>+ Create Ticket</button></div><HighlightBox label="ภาพรวมสถานะ" className="summary-highlight"><div className="metric-grid">{[["Total","286"],["New","18"],["In Progress","9"],["Closed","259"]].map(([k,v])=><div className={`metric metric--${k.toLowerCase().replace(" ", "-")}`} key={k}><span>{k}</span><b>{v}</b><small>tickets</small></div>)}</div></HighlightBox><div className="dashboard-grid"><HighlightBox label="แนวโน้มรายเดือน"><div className="panel chart-panel"><PanelTitle title="Monthly Trend" detail="Incident volume · 12 months"/><div className="bar-chart">{bars.map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="chart-legend"><span>● Total</span><span>● Zabbix</span><span>● Manual</span></div></div></HighlightBox><div className="dashboard-side"><div className="panel"><PanelTitle title="Severity Summary" detail="Current month"/><MiniBars data={[["Critical",42],["High",68],["Average",37]]}/></div><div className="panel"><PanelTitle title="Ticket Source Summary" detail="All incoming channels"/><div className="source-row"><span><i className="orange"/> Zabbix <b>132</b></span><span><i className="blue"/> Manual <b>60</b></span></div></div></div></div><div className="dashboard-bottom"><div className="panel compact-panel"><PanelTitle title="Recent Activity" detail="Latest updates"/><div className="activity"><span>#4342</span><b>/var recovered 95% → 43%</b><StatusBadge status="Closed"/><small>now</small></div><div className="activity"><span>#4341</span><b>Disk I/O overloaded</b><StatusBadge status="In Progress"/><small>8m</small></div></div><div className="panel compact-panel"><PanelTitle title="Top Risk Hosts" detail="Repeated this month"/><div className="risk-mini"><b>HSVCRP01</b><span>116 alerts</span></div><div className="risk-mini"><b>HSVCSP01</b><span>30 alerts</span></div></div><div className="panel compact-panel"><PanelTitle title="Top Alerts" detail="Recurring patterns"/><div className="risk-mini danger"><b>CPU utilization</b><span>84×</span></div><div className="risk-mini warning"><b>Disk I/O</b><span>29×</span></div></div></div></div></BrowserMockup>;
}

function PanelTitle({ title, detail }: { title: string; detail: string }) { return <div className="panel-title"><div><b>{title}</b><small>{detail}</small></div><span>•••</span></div>; }
function MiniBars({ data }: { data: [string, number][] }) { return <div className="mini-bars">{data.map(([n,v])=><div key={n}><span>{n}<b>{v}</b></span><i><em style={{width:`${v}%`}}/></i></div>)}</div>; }

export function LoginMockup() {
  return <BrowserMockup title="Login"><div className="login-screen"><div className="login-card"><div className="login-logo">RJ</div><h3>Roo-Jaeng Login</h3><p>Sign in to access the incident dashboard</p><HighlightBox label="1 · Username"><label>Username<input readOnly value="demo.user" aria-label="Mock username"/></label></HighlightBox><HighlightBox label="2 · Password"><label>Password<input readOnly value="••••••••••" aria-label="Mock password"/></label></HighlightBox><HighlightBox label="3 · Login"><button type="button">Sign in</button></HighlightBox><small className="mock-disclaimer">Presentation mockup · ไม่มีการส่งข้อมูล</small></div></div></BrowserMockup>;
}

export function TicketListMockup() {
  return <BrowserMockup title="Tickets"><AppHeader active="Tickets"/><div className="app-page tickets-page"><div className="mock-title"><div><small>INCIDENT OPERATIONS</small><h3>Tickets</h3><p>Showing 1–100 of 3,248 tickets</p></div><button>+ New Ticket</button></div><HighlightBox label="ค้นหาและกรอง"><div className="filters"><div className="search"><Icon name="search"/><span>Search ticket, host or ID…</span></div>{["Status", "Source", "Host", "Assigned user"].map(x=><div className="select" key={x}>{x}<b>⌄</b></div>)}</div></HighlightBox><div className="ticket-table"><div className="tr th"><span>ID</span><span>Incident</span><span>Severity</span><span>Source</span><span>Assigned</span><span>Status</span></div>{ticketRows.map(row=><div className="tr" key={row.id}><span className="ticket-id">{row.id}</span><span><b>{row.title}</b><small>{row.host}</small></span><span className={`severity severity--${row.severity.toLowerCase()}`}>{row.severity}</span><span>{row.source}</span><span>{row.owner}</span><StatusBadge status={row.status}/></div>)}</div><div className="pagination"><span>100 / Total 3,248</span><div><button>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></div></div></div></BrowserMockup>;
}

export function ManualTicketMockup() {
  return <BrowserMockup title="New Ticket"><AppHeader active="Tickets"/><div className="app-page form-page"><div className="mock-title"><div><small>MANUAL WORKFLOW</small><h3>Create New Ticket</h3></div><StatusBadge status="New"/></div><div className="form-card"><div className="form-grid"><label className="wide">Title<input readOnly value="ตรวจสอบ Network latency"/></label><label>Host<input readOnly value="HS-NET-02"/></label><label>Severity<div className="fake-input">High <b>⌄</b></div></label><label>Assigned To<div className="fake-input">Kanda <b>⌄</b></div></label><label className="wide">Detail<textarea readOnly value="พบ latency สูงกว่าค่ามาตรฐาน ตรวจสอบเส้นทางและอุปกรณ์เครือข่าย"/></label></div><div className="form-actions"><button className="secondary">Cancel</button><button>Save Ticket</button></div></div></div></BrowserMockup>;
}

export function TicketDetailMockup() {
  const events = [["16:02","Alert received · Ticket created","System"],["16:03","Push notification sent","System"],["16:05","Assigned to Thyme","Thyme"],["16:08","Investigation started","Thyme"],["16:20","Recovered 95% → 43% · Closed","System"]];
  return <BrowserMockup title="Ticket #4342"><AppHeader active="Tickets"/><div className="app-page detail-page"><div className="detail-head"><div><small>TICKET #4342</small><h3>/var filesystem usage reached 95%</h3><p>Host: HSVCRP01</p></div><StatusBadge status="Closed"/></div><div className="info-grid">{[["Severity","Warning"],["Source","Zabbix"],["Assigned To","Thyme"],["Created","04 Aug · 16:02"],["Updated","04 Aug · 16:20"]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><div className="state-flow"><StatusBadge status="New"/><i>→</i><StatusBadge status="In Progress"/><i>→</i><StatusBadge status="Closed"/></div><div className="tabs">{["Detail","Timeline","Notes","Work Log","Related"].map((x,i)=><span className={i===1?"active":""} key={x}>{x}</span>)}</div><div className="timeline">{events.map(([time,title,by],i)=><div key={title} className={i===events.length-1?"done":""}><i/><time>{time}</time><b>{title}</b><span>{by}</span></div>)}</div></div></BrowserMockup>;
}

export function ReportsMockup() {
  const bars=[38,54,45,68,61,82,72,91];
  return <BrowserMockup title="Reports"><AppHeader active="Reports"/><div className="app-page report-page"><div className="mock-title"><div><small>MONTHLY REPORT</small><h3>Incident Summary · August</h3></div><div className="select">August 2026 <b>⌄</b></div></div><div className="metric-grid compact">{[["Total","286"],["New","18"],["In Progress","9"],["Closed","259"]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><b>{v}</b></div>)}</div><div className="report-grid"><div className="panel"><PanelTitle title="Monthly trend" detail="Incident volume"/><div className="line-chart"><svg viewBox="0 0 500 130" role="img" aria-label="Monthly incident trend"><path className="area" d="M0 115 L0 95 L70 78 L140 87 L210 60 L280 68 L350 35 L420 47 L500 18 L500 115 Z"/><path className="line" d="M0 95 L70 78 L140 87 L210 60 L280 68 L350 35 L420 47 L500 18"/>{bars.map((_,i)=><circle key={i} cx={i*(500/7)} cy={[95,78,87,60,68,35,47,18][i]} r="4"/>)}</svg></div></div><div className="panel"><PanelTitle title="Source" detail="Tickets by channel"/><div className="donut"><div><span>46%</span></div><ul><li><i className="orange"/> Zabbix <b>132</b></li><li><i className="blue"/> Commvault <b>94</b></li><li><i className="green"/> Manual <b>60</b></li></ul></div></div></div><div className="team-table"><div><b>Team member</b><b>Work count</b><b>Work hours</b><b>Closed</b></div>{[["Narin","82","44.5 h","79"],["Kanda","76","39.0 h","70"],["Preecha","68","36.5 h","63"]].map(r=><div key={r[0]}>{r.map((x,i)=><span key={x}>{i===0?<><i>{x[0]}</i><b>{x}</b></>:x}</span>)}</div>)}</div></div></BrowserMockup>;
}

export function ZabbixRiskMockup() {
  return <BrowserMockup title="Zabbix Risk"><AppHeader active="Zabbix Risk"/><div className="app-page risk-page"><div className="mock-title"><div><small>RISK INTELLIGENCE</small><h3>Repeated Zabbix Risk</h3><p>Alert patterns repeated 3+ times this month</p></div><button>Open Zabbix Alerts</button></div><div className="metric-grid compact risk-metrics"><div className="metric"><span>Repeated Alerts</span><b>86</b></div><div className="metric"><span>Top Risk Hosts</span><b>12</b></div><div className="metric"><span>Open Zabbix</span><b>6</b></div></div><div className="risk-table"><div className="risk-tr header"><span>Risk</span><span>Host</span><span>Repeated Trigger</span><span>Count</span><span>Open</span></div>{riskRows.map((r,i)=><div className="risk-tr" key={r.host}><span className={`rank rank-${i+1}`}>#{i+1}</span><b>{r.host}</b><span>{r.trigger}</span><strong>{r.count} ครั้ง</strong><StatusBadge status={r.open>1?"In Progress":"New"}/></div>)}</div><div className="root-cause"><Icon name="chart"/><div><b>จาก Pattern สู่ Root Cause</b><span>จัดลำดับ Host และ Trigger ที่ควรแก้เชิงป้องกันก่อน</span></div></div></div></BrowserMockup>;
}

export function NotificationSettingsMockup() {
  return <div className="settings-card"><div className="settings-title"><div className="settings-icon"><Icon name="bell"/></div><div><small>ROO-JAENG</small><h3>Notification Settings</h3></div><StatusBadge status="Subscribed"/></div><div className="settings-checks">{[["Browser Support","Supported"],["Standalone Mode","Yes"],["Permission","Allow"],["Registered Devices","1 device"]].map(([k,v])=><div key={k}><span><Icon name="check"/>{k}</span><b>{v}</b></div>)}</div><button>Enable Notifications</button><button className="secondary">Test Notification</button><div className="test-result"><Icon name="check"/><div><b>Test completed</b><span>Successful 1</span></div><strong>Failed 0</strong></div></div>;
}
